---
title: "Documenting things"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(reticulate)
```


## The power of README

README are not a new thing. They have been around computer projects since the early days. One great thing about the popularization of supporting the markdown syntax and its web rendering in most code repositories, is that you can move beyond a simple text file and start to present a compelling entry point to your project that can link to various parts and external resources.



## Making your code readable

It is important to make your code easy to read if you hope that others will reuse it. It starts with using a **consistent syntax** withing your scripts (at least within a project). 

- Here is a good style guide for R: http://adv-r.had.co.nz/Style.html
- Syle guide for Python: https://www.python.org/dev/peps/pep-0008/

```{python Zen of Python, echo=TRUE}
import this
```


There is also the **visual aspect** of the code that should not be neglected. Like a prose, if you receive a long text without any paragraphs, you might be not very excited about reading it. _Indentation_, _spaces_, and _empty lines_ should be leveraged to make a script visually inviting and easy to read. The good news is that most of the Integrated Development Environment (IDE) will help you to do so by auto formatting your scripts according to conventions.  Note that also a lot of IDEs, such as RStudio, rely on some conventions to ease the navigation of scripts and notebooks. For example, try to add four `-` or `#` after a line starting with one or several `#` in an R Script! 

## Comments

***Real Programmers don't comment their code. If it was hard to write, it should be hard to understand.*** \
_Tom Van Vleck, based on people he knew (https://multicians.org/thvv/realprogs.html)_

Joke aside, it is really hard to comment too much your code, because even steps that might seem trivial today might not feel like this anymore in a few weeks or months for now. In addition, a well commented code is more likely to be read by others.

### Inline 

### Functions



## Leveraging Notebooks

### A few thoughts on Notebooks and Scripts

## Metadata

### Human readable

### Machine readable

### Data provenance & semantics



# What about your computing environment

## Session info

## Containers

# Licensing

# Further reading

# Aknowledgements


