---
title: "Developing Analytical Workflows as a Team"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Day 2

| **Time (PST)**    | **Activity**                        |
|-------------------|-------------------------------------|
| 9:00am - 9:50am   | *Managing Data Science Project as a team (50 min)*        |
| 9:50am - 10:00am  | *Break (10 min)*                                        |
| 10:00am - 10:50am | *Coding together (50min)*        |
| 10:50am - 11:00am | *Break (10min)*                  |
| 11:00am - 12:00pm | *Flex time 1: Resumé Workshop (Myia) (60 min)*         |
| 12:00pm - 1:15pm  | *Lunch (75 min)*                                          |
| 1:15pm - 2:15pm   | *Review Forks, Branches and Pull Requests (60 min)*   |
| 2:15pm - 2:25pm   | *Break (10 min)*           |
| 3:15pm - 3:25pm   | *GitHub hands-on on server (70min)*                  |
| 3:25pm - 3:35pm   | *Day 2 Recap (10min)*       |
| 3:35pm - 5:00pm   | *Q&A with Casey*                      |


---

# Managing data-driven projects as a team

[**Materials**](day2-projects_team.html)



---

# Coding together

[**Materials**](day2-coding_together.html)


---

# Git Therapy

## GitHub conflicts

First thing to know is that actually `git pull` (or a Pull Request) is a two step process: `git pull = git fetch + git merge`

Second: you did nothing wrong!! Git tries to merge files automatically. When the changes are on the same file far apart, git will figure it out on his own and do the merge automatically. However if changes are overlapping, `git` will call you to the rescue and ask him how to solve the problem.

[**Materials**](day2-git-collaboration-conflicts.html)


---

# `git` commit messages

[**Materials**](day2-github_commit_messages.html)

---

# Further reading

## Collaborative coding

- A new grad's guide to coding as a team - Atlassian:
https://www.atlassian.com/blog/wp-content/uploads/HelloWorldEbook.pdf 
- 10 tips for efficient programming: 
https://www.devx.com/enterprise/top-10-tips-for-efficient-team-coding.html 
- Agile Manifesto: https://moodle2019-20.ua.es/moodle/pluginfile.php/2213/mod_resource/content/2/agile-manifesto.pdf

## Code Review

- Small-Group Code Reviews For Education: https://cacm.acm.org/blogs/blog-cacm/175944-small-group-code-reviews-for-education/fulltext

## Branches

- Interactive tutorial to learn more about git branches and more <https://learngitbranching.js.org/>

## GitHub Workflow

- GitHub:
   - guides on how to use GitHub: [https://guides.github.com/](https://guides.github.com/)
   - GitHub from RStudio: [http://r-pkgs.had.co.nz/git.html#git-pull](http://r-pkgs.had.co.nz/git.html#git-pull)
- Forking:
   - [https://help.github.com/articles/fork-a-repo/](https://help.github.com/articles/fork-a-repo/)
   - [https://guides.github.com/activities/forking/](https://guides.github.com/activities/forking/)
- Comparison of git repository host services: <https://www.git-tower.com/blog/git-hosting-services-compared/>
- Branches
   - interactive tutorial on branches: <http://learngitbranching.js.org/>
   - using git in a collaborative environment: <https://www.atlassian.com/git/tutorials/comparing-workflows/centralized-workflow>
https://moodle2019-20.ua.es/moodle/pluginfile.php/2213/mod_resource/content/2/agile-manifesto.pdf 

### Git using RStudio

- Happy Git and GitHub for the useR: http://happygitwithr.com/
- R packages - Git and GitHub: http://r-pkgs.had.co.nz/git.html#git-init
 
Git mainly from the command line:

- Interactive git 101: [https://try.github.io/](https://try.github.io/)
- Very good tutorial about git: [https://www.atlassian.com/git/tutorials/what-is-version-control](https://www.atlassian.com/git/tutorials/what-is-version-control)
- Git tutorial geared towards scientists: [http://nyuccl.org/pages/gittutorial/](http://nyuccl.org/pages/gittutorial/)
- Short intro to git basics: [https://github.com/mbjones/gitbasics](https://github.com/mbjones/gitbasics)
- Git documentation about the basics: [http://gitref.org/basic/](http://gitref.org/basic/)
- Git documentation - the basics: [https://git-scm.com/book/en/v2/Getting-Started-Git-Basics](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics)
- Git terminology: [https://www.atlassian.com/git/glossary/terminology](https://www.atlassian.com/git/glossary/terminology)
- In trouble, guide to know what to do: [http://justinhileman.info/article/git-pretty/git-pretty.png](http://justinhileman.info/article/git-pretty/git-pretty.png)
- Want to undo something? <https://github.com/blog/2019-how-to-undo-almost-anything-with-git> 
- Git terminology: <https://www.atlassian.com/git/glossary/terminology>
- 8 tips to work better with git: <https://about.gitlab.com/2015/02/19/8-tips-to-help-you-work-better-with-git/>
- GitPro book (2nd edition): <https://git-scm.com/book/en/v2>


### Undoing things

- Help to decide how to undo your problem: <http://justinhileman.info/article/git-pretty/git-pretty.png>
- Undo almost everything with git <https://blog.github.com/2015-06-08-how-to-undo-almost-anything-with-git/>
- Difference between git reset soft, mixed and hard <https://davidzych.com/difference-between-git-reset-soft-mixed-and-hard/>
- Resetting, Checking Out & Reverting <https://www.atlassian.com/git/tutorials/resetting-checking-out-and-reverting>

