---
title: "Scientific Programming as a Team"
---

# Day 4

| **Time (PST)**    | **Activity**                        |
|-------------------|-------------------------------------|
| 9:00am - 9:30am   | *Recap of yesterday*                    |
| 9:30am - 10:05am  | *Pair programming*                      |
| 10:05am - 10:15am | *Break 1 (10 min)*                      |
| 10:15am - 11:00am | *Meet your next Instructor -- Jim Frew* |
| 11:00am - 12:00pm | *Group project*                        |
| 12:00pm - 1:15pm  | *Lunch (75 min)*                       |
| 1:15pm - 2:15pm   | *Documenting things (60 min)*          |
| 2:15pm - 3:00pm   | *Capstone projects -- Jamie*           |
| 3:00pm - 3:10pm   | *Break*                                |
| 3:10pm - 4:30pm   | *Group project*                        |
| 4:30pm -          | *Happy hour with Ginger ;)*            |

# Coding as a team

## Code ~~review~~ feedback

Code review is an *asynchronous* team activity. Despite its impressive name, code review should be seen by the person asking for the review (submitter) as a great opportunity to have one more pair of eyes looking at your code and providing feedback to make your code better. The "reviewer" should see this activity as a great way to learn from others.

You actually have already practice this a little when practicing merging pull request!!


## Pair programming

[*Material*](day4-pair_programming.html)


## A few more thoughts on coding together

### More is not always better

- Adding more analysts late into a project can be counterproductive ([Brooks’ law](https://en.wikipedia.org/wiki/Brooks%27s_law))
- Overtime is not the solution as it will increase likeliness of errors and thus frustration. Try to focus on finding at what time of the day you are the most productive at coding instead

### Project management

This is a big topic and will be highly influenced by the team you are working with both in terms of practices and tools used to manage the project. On the coding side, there is a lot to borrow from Agile development approach for scientist. In a nutshell: "put it out there fast and iterate". In other words to wait to try to have the perfect code or analysis before sharing it with your collaborators. It is more efficient to share and discuss an early / draft version, gather feedback and iterate.


---


# Documenting things

[**Materials**](day4-documenting.html)

